name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to WiFiDuck and thanks for your first issue and helping us to make our software better'' first issue'
        pr-message: 'Welcome to WiFiDuck and thanks for your first pull request and helping us to make our software better'' first pr'
